name: SonarQube Scan

on:
  push:
    branches:
      - DEV

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v1
      env:
        SONAR_TOKEN: "squ_3fa74690c0b6c7920fec1d8b891d37692098e613"
        SONAR_HOST_URL: "http://localhost:9000"
